import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="p-4 flex gap-4">
          <Link href="/basic">Basic</Link>
          <Link href="/auto-focused">Auto-Focused</Link>
        </nav>
        <div className="flex flex-col gap-6 max-w-screen-md mx-auto my-6">
          {children}
        </div>
      </body>
    </html>
  );
}
